### ISSUE TITLE
Cosmos SDK and Tendermint glossary 

### ISSUE THREAD

**Issue by barriebyron** [cosmos/advocates#13]
Mission: Develop a single source of truth glossary for Tendermint and Cosmos SDK.

Because a published glossary exists, we will focus on improving the published glossary [https://cosmos.network/glossary](https://cosmos.network/glossary)

As of April 2021, Stargate new website is live but this [cosmos.network](https://cosmos.network/glossary) glossary is still v1 and on the design team list. Curiously, the glossary is sourced in two places for two purposes.
See Cyrus [comment in this PR](https://github.com/cosmos/advocates/issues/13#issuecomment-799699835)

**Comment by barriebyron** [comment]
@Tosch110 @okwme do we have working glossaries anywhere else?

**Comment by lovincyrus** [comment]
@barriebyron, ~~I believe the airtable glossary list has been deprecated for awhile now.~~ We're currently using https://github.com/tendermint/cosmos-ui/blob/develop/src/Tooltip/dict.json for the [`cosmos.network/glossary`](https://cosmos.network/glossary)

The idea was to create a custom tooltip to map a new glossary list on [`cosmos.network/intro`](https://cosmos.network/intro)

## Updates:
`/glossary`
- it's using this list https://github.com/cosmos/cosmos.network/blob/develop/assets/data/dict.json ~~https://github.com/tendermint/cosmos-ui/blob/develop/src/Tooltip/dict.json~~
- https://github.com/cosmos/cosmos.network/blob/develop/src/views/Glossary.vue#L15

`/intro`
- it's using airtable glossary list
- (1) https://github.com/cosmos/cosmos.network/blob/develop/src/views/Intro.vue#L34
- (2) https://github.com/cosmos/cosmos.network/blob/develop/src/store/modules/glossary.js#L15

**Comment by barriebyron** [comment]
@lovincyrus thanks for this update... Help me understand the status of this glossary. We can rely on this glossary for current and future use? I am digging the tooltips on https://cosmos.network/intro 

I think the answer is no, but can we have tooltips from Markdown docs?

**Comment by lovincyrus** [comment]
> We can rely on this glossary for current and future use?

Yes, we can use the list. Now that I think about it, the JSON file was created just so that we could fetch the key value directly without relying the data from Airtable glossary list. They might be _identical_.

> but can we have tooltips from Markdown docs?

Are you suggesting that we should use a markdown file instead of JSON? Which markdown docs are you referring to?

**Comment by barriebyron** [comment]
@lovincyrus  open to ideas! I am in early stages of gathering information and understanding what we have. I want a discoverable Cosmos SDK glossary that is the single source of accurate truth.

**Comment by lovincyrus** [comment]
You can update the airtable glossary list for the time being since it's easier to maintain than dealing with JSON syntax. 🆗

**Comment by barriebyron** [comment]
@lovincyrus  I didn't see your comment above about the airtable glossary, and instead updated the JSON in https://github.com/tendermint/cosmos-ui/pull/218

**Comment by barriebyron** [comment]
UPDATE: 

> For easy "let's all add terms and definitions" at first I created a [collaborative universal glossary](https://docs.google.com/spreadsheets/d/1vONTXeKIDYC-6vy98kjQQjF9cigbFGmqtJ7WbIWT2Tc/edit#gid=0) sheet but 

that effort too got lost in a shuffle. Let's focus only on updating the actual source in the json and airtable

**Comment by barriebyron** [comment]
Cyrus pointed me to the published glossary https://v1.cosmos.network/glossary

**Comment by barriebyron** [comment]
Cyrus
old site starts with v1 
a lot of people visit the old [v1 intro](https://v1.cosmos.network/intro)
hover to see definition list

the current definition list is accessed from two places:
/intro
/glossary

right now, this content is not streamlined for the new website. As @lovincyrus explained earlier in this PR, the glossary is sourced from: airtable (legacy, deprecated) and json 

Cyrus is going to bump the glossary version and update the glossary to be the new cosmos.network. We don't yet know how the airtable vs json is going to be resolved, it's a work in progress. We do need improved SEO (I didn't even know we had a glossary)

To add new definitions, use a PR for https://github.com/tendermint/cosmos-ui/blob/develop/src/Tooltip/dict.json  and ping in #ecodev and get other eyes on it

Cyrus will consolidate into one source and let me know which source.

**Comment by lovincyrus** [comment]
Update: The [`v1.cosmos.network/glossary`](http://v1.cosmos.network/glossary) has been bumped in this PR https://github.com/cosmos/v1.cosmos.network/pull/194 ✔️ 

JSON file: https://github.com/tendermint/cosmos-ui/blob/develop/src/Tooltip/dict.json

Now that we're slowly moving away from [`cosmos-ui`](https://github.com/tendermint/cosmos-ui), it makes sense that we relocate the JSON file to elsewhere. The best home for the file is this repo — `cosmos/advocates`. This omits the need to create another repo. We could also implement a process in which we can introduce/suggest a new definition → review → approve → gets added to the list.

The JSON file will be used in the new [`cosmos.network`](http://cosmos.network/) and old [`v1.cosmos.network/glossary`](https://v1.cosmos.network/glossary). As we're putting in the works in rolling out the new `cosmos.network/intro`, there is no need to maintain [the Airtable Glossary](https://airtable.com/tbltEIRH9YJ8yE3PP/viw5ohOPNAk6ld1Ig?blocks=hide).

## Next steps:
- [x] Cyrus to add the JSON file to this repo

**Comment by barriebyron** [comment]
TIL about https://github.com/orgs/cosmos/teams
