### ISSUE TITLE
cosmos-sdk docs broken from search

### ISSUE THREAD

**Issue by charleenfei** [cosmos/advocates#19]
if you google into the docs, most of the links that show up first are broken bc they link you to ‘master’ and not the latest version. for example: https://docs.cosmos.network/master/modules/upgrade/ vs https://docs.cosmos.network/v0.42/modules/upgrade/#upgrade

maybe we can redirect master to the latest version in order to not lose the seo?

**Comment by tac0turtle** [comment]
master breaking was an oversight of a spec PR. It should be fixed here https://github.com/cosmos/cosmos-sdk/pull/9121

**Comment by tac0turtle** [comment]
Fixed!!! 🥳  thank you @lovincyrus 

- https://docs.cosmos.network/master/basics/app-anatomy.html
